### ISSUE TITLE
Error when I secondly run slater watch command

### ISSUE THREAD

**Issue by kelfy** [the-couch/slater#37]
This is first time I am using slater. When I first run "slater watch" which is fine. After I run "slater sync" then I come back and run "slater watch", the following error occur.

I've tried delete and whole theme and re-initialise the theme 3 times but no luck. Not sure what kind of error it is.

````````````````
slater v1.4.1

watch development theme (https://xxxxx.myshopify.com/?fts=0&preview_theme_id=99999999999)

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Object.watch (/usr/local/lib/node_modules/slater/node_modules/@slater/compiler/index.js:81:10)
    at watch (/usr/local/lib/node_modules/slater/index.js:202:23)
    at <anonymous>
````````````````

**Comment by estrattonbailey** [comment]
@kelfy thanks! I'll have a look at this.

**Comment by estrattonbailey** [comment]
@kelfy what OS and Node version are you on?

Also, would you mind trying something for me? Run `slater watch`, then `slater sync`, and *then* try opening `https://localhost:4000` and let me know what you see.

`:4000` is the port we use for live-reloading. It's possible that when those initial build and sync processes exit, the aren't closing the server properly. That could be caused by a number of things, including OS and Node versions.

**Comment by tomaszbujnowicz** [comment]
I can also confirm that I have the same issue when running two instances of slater in the same time. When I switch between themes, I need to shut one of them down to work on another one. Anyway, it's nothing serious.

**Comment by kelfy** [comment]
Thank you so much. Never thought about that. cheers for the comments.

**Comment by estrattonbailey** [comment]
@kelfy hey no problem :) is your issue solved then?

**Comment by kelfy** [comment]
@estrattonbailey not entirely solved but managed to get around the problem by restart the terminal.

**Comment by estrattonbailey** [comment]
@kelfy I'm sure there is. Would you mind having a look at my [previous response](https://github.com/the-couch/slater/issues/37#issuecomment-498260489) and answering those questions? That would be super helpful. Thanks!

**Comment by kelfy** [comment]
@estrattonbailey I tried but nothing showing up. DIdn't notice it got live-reload.  I am sure my theme is alright as I can browse online.
