### ISSUE TITLE
listen EADDRINUSE: address already in use :::4000

### ISSUE THREAD

**Issue by jcast90** [the-couch/slater#84]
I've been using for the past few months and it's been awesome! However, I probably haven't used it in the past month or 2, when I came back to start a new project I keep getting this error:

`Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1301:14)
    at listenInCluster (net.js:1349:12)
    at Server.listen (net.js:1437:7)
    at Object.watch (/Users/usr/Desktop/freelance/new-store/node_modules/@slater/compiler/index.js:81:10)
    at watch (/Users/user/Desktop/freelance/new-store/node_modules/slater/index.js:222:25)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1328:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 4000
}`

I tried doing removing any other global slater installs and re-installed everything  and tried with a brand new store and still am getting this issue. When I try and run` lsof -ti:4000` it's not showing anything is running on this port.  Has anyone else had issues with this or found a solution?

Again, awesome job on this project, it makes shopify dev so much more convenient!

**Comment by jcast90** [comment]
UPDATE: I was able to resolve this by going to `node_modules/@slater/compiler/index.js ` and changing the port to `4040`. This is a temporary  fix, again  not sure if anybody else is having this issue, but the watch command seems to conflict with some other command being ran on port 4000.  Should the commands be running on separate ports, or  maybe add in a condition to check if something conflicts with another port then it'll just run on the next open port?

**Comment by iamkevingreen** [comment]
@jcast90 I haven't encountered this issue particularly with slater, but I have encountered my system not closing other ports (gatsby sites, netlify dev etc). I use an npm package called [fkill](https://www.npmjs.com/package/fkill) to close specific ports running. Might be a bandaid to a system problem but it works for my purposes

**Comment by kith-and-kin** [comment]
This often happens when a process running on that particular port hasn't terminated properly.
The fact that it's port 4000 being used means it's more than likely just from a previous time you've spun up Slater and perhaps it's crashed, or not been shut down correctly.

In terminal write:

`sudo lsof -i :4000`

This finds all processes running on that port.
You'll see a column called PID. Find the PID that seems to be causing the issue then run:

`kill -15 PID` (replacing PID in that command with the actual PID).

This should stop the process that's running on that port and allow you to spin Slater back up.

**Comment by jcast90** [comment]
@iamkevingreen @kith-and-kin Thanks for the responses! I did that and killed all process running on that port. What seems to be happening is it runs on that port and fails or something but continues to run? So I first check if anything is running on port 4000, nothing shows up, then when I run it, it shows that error, then I check again if anything is running on that port, kill it, then run it again but same error. So bizarre. Might close this if no one else is experience this issue.

**Comment by kith-and-kin** [comment]
No worries! It's probably worth leaving it open for now, as there is another issue reported here #37, so there's probably some substance.

**Comment by Mohammed-Elkhamlichi** [comment]
just exit from the current terminal and open an other one and this problem will solved

**Comment by Dhei-vid** [comment]
On windows, you can see the TCP connections on your system with the command `netstat -ano`. Then find and display the line showing information about the TCP process listening on TCP port 4000 with the command `findstr :8080`. You should get an output like;

` TCP     0.0.0.0:4000    0.0.0.0:0   LISTENING   2660`
` TCP     [::]:4000   [::]:0      LISTENING   2660`

The final number on both lines is the process ID (PID) of the process using port 8080. Using this PID, we can end the process with taskkill. 

`taskkill /PID 2660 /F`

Run your server after completing the following.
