### ISSUE TITLE
Errors on slater watch and build commands

### ISSUE THREAD

**Issue by blimpmason** [the-couch/slater#85]
I'm getting an error right out of the gate on a clean instance based on the starter repo with no changes besides required slater.config.js entries. I've triple checked my slater.config settings. 

What's really weird is I've tried using the same Shopify settings for testing as another local repo that is not throwing these errors (though I get the same error with that working repo if I use the slater CLI commands directly rather than using `npm run start` or `yarn start`). 

Here's the error on `npm run start` (slater watch):
```
> @slater/theme@1.1.3 start /Users/davidgross/Sites/slater-test
> slater watch --config slater.config.js

watching 
syncing development theme (https://bluelandhome.myshopify.com/?fts=0&preview_theme_id=81049288759)
(node:94851) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at watch (/Users/davidgross/Sites/slater-test/node_modules/@slater/cli/index.js:189:24)
(node:94851) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:94851) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And here's the error on `npm run build` (slater build):
```
> @slater/theme@1.1.3 build /Users/davidgross/Sites/slater-test
> slater build --config slater.config.js

@slater/cli building 
(node:94769) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.resolve (path.js:980:7)
    at resolve (/Users/davidgross/Sites/slater-test/node_modules/@friendsof/spaghetti/util.js:23:15)
    at module.exports (/Users/davidgross/Sites/slater-test/node_modules/@friendsof/spaghetti/index.js:71:12)
    at /Users/davidgross/Sites/slater-test/node_modules/@slater/cli/index.js:94:9
    at new Promise (<anonymous>)
    at build (/Users/davidgross/Sites/slater-test/node_modules/@slater/cli/index.js:93:14)
(node:94769) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:94769) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm running node v13.12.0, npm 6.14.4, and yarn 1.22.4.

Has anyone else encountered this issue?

**Comment by blimpmason** [comment]
I found #11  after looking through some closed issues and just wanted to clarify I'm on Mac OS 10.13.6, not Windows, though the errors look very similar.

**Comment by blimpmason** [comment]
I reinstalled slater globally and now I no longer get errors when using the slater CLI commands directly ie `slater watch` and `slater build` (!!!), but I still get the errors when using `npm run start` / `yarn start`  and `npm run build` / `yarn build` despite boilerplate scripts in package.json:

```
"scripts": {
		"start": "slater watch",
		"build": "slater build",
		"deploy:development": "slater build && slater sync",
		"deploy:production": "slater build && slater sync --theme production"
	},
```

**Comment by blimpmason** [comment]
Ok, after reinstalling slater globally I tried initializing a fresh instance and all my problems have gone away!

**Comment by aeblin** [comment]
Just nudging that I'm getting this currently and reinitializing/reinstalling Slater globally isn't sorting it out.

Seems to be well past time to move on from Slater, but would be nice to be able to support legacy projects still.
